services:
  frontend:
    build:
      context: ./frontend
    container_name: expense_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://13.53.53.18:5000
    restart: always
    networks:
      - expense-network

  backend:
    build:
      context: .
    container_name: expense_backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    networks:
      - expense-network

  mysql:
    image: mysql:8.0
    container_name: expense_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - expense-network

volumes:
  mysql_data:

networks:
  expense-network:
